apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /   # Adjust if needed
spec:
  ingressClassName: nginx
  rules:
  - host: rakanprojects.com   # Same domain
    http:
      paths:
      - path: /items   # Path for backend service
        pathType: Prefix
        backend:
          service:
            name: mongo-backend-service
            port:
              number: 80
