apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-mongo-ingress
  namespace: backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: items.rakanprojects.com
    http:
      paths:
      - path: /items
        pathType: Prefix
        backend:
          service:
            name: mongo-backend-service
            port:
              number: 80
