apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-access
  namespace: backend
spec:
  podSelector:
    matchLabels:
      app: mongo-backend-service
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: frontend
    ports:
    - protocol: TCP
      port: 80
  policyTypes:
  - Ingress
